"""Reference list of Path of Exile 1 chat slash-commands, offered as a
quick-insert pool in the chat-macro tab (source: PoEDB's commands list,
cross-checked against the official forum's chat-commands thread). Commands
that take an argument keep a trailing space so the cursor lands ready to
type a name/number after inserting."""
from __future__ import annotations

# (command text, description)
POE1_COMMANDS: list[tuple[str, str]] = [
    ("/played", "현재 캐릭터의 플레이 시간을 표시합니다."),
    ("/age", "캐릭터를 생성한 지 얼마나 지났는지 표시합니다."),
    ("/remaining", "현재 맵에 남은 몬스터 수를 표시합니다."),
    ("/deaths", "캐릭터의 사망 횟수를 표시합니다."),
    ("/kills", "획득한 경험치 킬 수를 표시합니다."),
    ("/passives", "패시브 스킬 포인트 사용 내역을 표시합니다."),
    ("/atlaspassives", "아틀라스 패시브 스킬 포인트 사용 내역을 표시합니다."),
    ("/pvp", "PvP 모드를 활성화합니다."),
    ("/ladder", "현재 래더 상위 10명을 표시합니다."),
    ("/oos", "서버와 강제로 동기화를 재시도합니다 (Out of Sync)."),
    ("/oosme", "자신에 대해서만 동기화를 재시도합니다."),
    ("/destroy", "커서에 들고 있는 아이템을 파괴합니다."),
    ("/whois ", "이름으로 캐릭터 정보(레벨/리그 등)를 조회합니다."),
    ("/itemlevel", "커서에 들고 있는 아이템의 아이템 레벨을 표시합니다."),
    ("/fixmyhelmet", "투구 모델을 최신 상태로 갱신합니다."),
    ("/bug", "버그를 신고하고 참조 번호를 받습니다."),
    ("/debug", "디버그 모드를 켭니다."),
    ("/help", "채팅 명령어 도움말을 표시합니다."),
    ("/status ", "내 상태 메시지를 설정합니다."),
    ("/autoreply ", "귓속말에 자동으로 보낼 답장 문구를 설정합니다."),
    ("/afk", "자리비움(AFK) 자동 답장을 켭니다."),
    ("/dnd", "방해금지 상태로 설정하고 귓속말을 무시합니다."),
    ("/donotdisturb", "방해금지 상태로 설정합니다."),
    ("/nochat", "채팅 표시를 끕니다."),
    ("/togglenochat", "채팅 표시를 켜고 끕니다."),
    ("/cls", "채팅창을 지웁니다."),
    ("/clear", "채팅창을 지웁니다."),
    ("/global ", "지정한 번호의 글로벌 채널로 이동합니다."),
    ("/trade ", "지정한 번호의 거래 채널로 이동합니다."),
    ("/friend ", "이름으로 친구 목록에 추가합니다."),
    ("/unfriend ", "친구 목록에서 제거합니다."),
    ("/ignore ", "이름으로 해당 플레이어를 차단합니다."),
    ("/unignore ", "차단을 해제합니다."),
    ("/squelch ", "해당 플레이어의 채팅을 숨깁니다."),
    ("/unsquelch ", "숨김을 해제합니다."),
    ("/clear_ignore_list", "차단 목록을 모두 비웁니다."),
    ("/invite ", "이름으로 파티에 초대합니다."),
    ("/accept", "받은 초대를 수락합니다."),
    ("/kick ", "이름으로 파티에서 추방합니다."),
    ("/leave", "현재 파티를 나갑니다."),
    ("/party_description ", "파티 설명 문구를 설정합니다."),
    ("/tradewith ", "이름으로 거래를 신청합니다."),
    ("/guild ", "길드 관련 명령을 실행합니다."),
    ("/invitetohideout ", "이름으로 내 거처에 초대합니다."),
    ("/spectate ", "이름으로 관전을 요청합니다."),
    ("/hideout", "내 거처로 이동합니다."),
    ("/town", "마을(거처)로 이동합니다."),
    ("/menagerie", "동물원(비스트 보관함)으로 이동합니다."),
    ("/delve", "TSA(어젠다/딜브)로 이동합니다."),
    ("/sanctum", "생추어리(고행)로 이동합니다."),
    ("/synthesis", "합성 콘텐츠로 이동합니다."),
    ("/heist", "하이스트 콘텐츠로 이동합니다."),
    ("/necropolis", "네크로폴리스 콘텐츠로 이동합니다."),
    ("/monastery", "수도원 콘텐츠로 이동합니다."),
    ("/kingsmarch", "킹스마치 콘텐츠로 이동합니다."),
    ("/boat", "이동 수단(보트)에 탑승합니다."),
    ("/save_hideout", "현재 거처 배치를 파일로 저장합니다."),
    ("/dance", "댄스 이모트를 실행합니다."),
    ("/itemfilter ", "이름으로 지정한 아이템 필터로 즉시 전환합니다."),
    ("/reloaditemfilter", "현재 적용된 아이템 필터를 새로고침합니다."),
    ("/reset_xp", "시간당 경험치 계산을 초기화합니다."),
    ("/recheck_achievements", "특정 업적을 다시 확인합니다."),
    ("/feedback ", "개발팀에 피드백을 전송합니다."),
    ("/verify", "계정 인증을 진행합니다."),
    ("/deletelockedmap", "잠긴 맵을 제거합니다."),
    ("/recoveroldcraftingbenchitem", "제작대에 유실된 아이템을 복구합니다."),
    ("/convertracereward", "레이스 보상을 변환합니다."),
    ("/reclaim_guild_tag_items", "길드 태그가 붙은 아이템을 회수합니다."),
    ("/exit", "게임 클라이언트를 종료합니다."),
]
