"""Item price checking against the official trade site.

Four pieces, deliberately separated so each can be tested without the others:

:mod:`gamedata`
    The game's own modifier, base-type and client-label tables, read from
    ``data/trade/<language>/``. Everything about understanding a Korean item
    is answered from here, offline, before the site is spoken to at all.
:mod:`item`
    Turns the text the game puts on the clipboard into a structured item,
    resolving each line against :mod:`gamedata` as it goes.
:mod:`query`
    Turns that item, plus whatever the user ticked, into a search the site
    understands.
:mod:`api`
    Talks to the trade site: what this realm accepts, how it spells a name,
    the search itself, and the bulk exchange.

The data files are generated by Awakened PoE Trade (MIT licensed) from the
game's own data; ``tools/update_trade_data.py`` refreshes them and
:func:`gamedata.refresh` keeps them current at runtime. See THIRD_PARTY.md.
"""
